### ISSUE TITLE
Probelms of GPU acceleration

### ISSUE THREAD

**Issue by gorillaleap** [cabooster/DeepCAD#6]
Hi,
     Thanks for providing us the ImageJ plugin. I had one question about GPU acceleration. I already followed the pipeline listed here. But when I am using DeepCAD to process my images, ImageJ only takes 1% GPU but 60% CPU (No warning about only using CPU). I selected TensorFlow 1.15.0 GPU in the ImageJ and installed TensorFlow 2. How could I use my GPU for computation in ImageJ?

**Comment by cabooster** [comment]
Thanks for your feedback. It seems that your Fiji is not using GPU. The GPU support of CSBDeep is not so general and problems would vary from device to device. Linux seems to have fewer problems.

**Comment by psaha001** [comment]
Hello, 
Thank for providing us the ImageJ plugin. I have installed the DeepCAD package and it runs perfectly on both test data (tif file 256*256*320  and 256*256*1000). But I cannot make it run on my data.
My file specification : Dimension: 512 * 495
Width: 512
Bit depth: 16
file type: tif
can you give some insight into what changes should I make to run my data?
#I have tried changing stack size in x/stack size in y/stack size in z.

Thank you
Pritom

**Comment by psaha001** [comment]
![git](https://user-images.githubusercontent.com/77687377/130283965-fbc14257-95e8-4946-8f21-56fa41f4971a.JPG)

This the error.

**Comment by cabooster** [comment]
Hi, does it work if you use the default parameters? The `stack size`  is actually the patch size. Sorry for the confusing parameter names.

**Comment by gorillaleap** [comment]
Sorry, Another Thing. I could not find .yaml file in the ModelForPytorch google folder.

**Comment by gorillaleap** [comment]
Hi, following the guideline, when I am running the Pytorch code using Linux. (This line: python script.py test), there is an error. Could you give me some advice?
![image](https://user-images.githubusercontent.com/88165643/130725129-02fbf0aa-78b3-47fc-92e5-e8cdc4ad70d4.png)

**Comment by cabooster** [comment]
> Hi, following the guideline, when I am running the Pytorch code using Linux. (This line: python script.py test), there is an error. Could you give me some advice?
> ![image](https://user-images.githubusercontent.com/88165643/130725129-02fbf0aa-78b3-47fc-92e5-e8cdc4ad70d4.png)

Hi,  gorillaleap. You should delete other files in `DataForPytorch`. There is a placeholder file in it since empty folders are not allowed in GitHub. By the way, an **updated version** of the Pytorch code has been recently released at https://github.com/cabooster/DeepCAD-RT. This new version has several new features such as much faster processing speed, low memory cost, improved pre- and post-processing, multi-GPU acceleration, more stable performance, etc. You can try it for better convenience. I hope it can help you.

**Comment by cabooster** [comment]
Hi,  gorillaleap. You should delete other files in `DataForPytorch`. There is a placeholder file in it since empty folders are not allowed in GitHub. By the way, an **updated version** of the Pytorch code has been recently released at https://github.com/cabooster/DeepCAD-RT. This new version has several new features such as much faster processing speed, low memory cost, improved pre- and post-processing, multi-GPU acceleration, more stable performance, etc. You can try it for better convenience. I hope it can help you.

> Hi, following the guideline, when I am running the Pytorch code using Linux. (This line: python script.py test), there is an error. Could you give me some advice?
> ![image](https://user-images.githubusercontent.com/88165643/130725129-02fbf0aa-78b3-47fc-92e5-e8cdc4ad70d4.png)

Hi,  gorillaleap. You should delete other files in `DataForPytorch`. There is a placeholder file in it since empty folders are not allowed in GitHub. By the way, an **upgraded version** of the Pytorch code has been recently released at https://github.com/cabooster/DeepCAD-RT. This new version has several new features such as much faster processing speed, low memory cost, improved pre- and post-processing, multi-GPU acceleration, more stable performance, etc. You can try it for better convenience. I hope it can help you.

**Comment by cabooster** [comment]
> Hi, following the guideline, when I am running the Pytorch code using Linux. (This line: python script.py test), there is an error. Could you give me some advice?
> ![image](https://user-images.githubusercontent.com/88165643/130725129-02fbf0aa-78b3-47fc-92e5-e8cdc4ad70d4.png)
